### ISSUE TITLE
Static width of blocks

### ISSUE THREAD

**Issue by radeusgd** [radrow/i3hloc#1]
Some blocks change their width very often, depending on the amount of text in them (for example the network usage is sometimes very small and sometimes quite big), that makes all blocks to the left of that one shift which can be unpleasant if it happens continuously.

I'd suggest adding an option of making a block have a constant minimum width, so that even if it has less content it wouldn't shrink thus keeping blocks to its left stationary.

**Comment by radrow** [comment]
Should be working since last commit. Desired option may be set by adjusting `maxChars` and `minChars` fields in config sections. However it won't work perfect unless you use fixed-size font
